version: "3.9"  # optional since v1.27.0
services:
  my-app:
    image: guycohen85/backend-my-app:1.0
    #build: .
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - PORT=3001
      - APP_DB=mongodb://my-app:password@mongodb/my-app
      - JWT_SECRET=<JVLUlb$0p^QBtzBj7Pm9oF.j<^h

  mongodb:
    # open mongodb terminal and add a user to a database (Find a way to automate this for initial db)
    # mongosh mongodb://admin:password@127.0.0.1:27017/admin
    # use my-app
    # db.createUser({user:"my-app", pwd:"password", roles:[{role:"readWrite", db:"my-app"}]})
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
volumes:
  mongodb-data: