
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzM0NDg1ODgsImV4cCI6MTY3NDA1MzM4OH0.k4-rHHhgsolE689fU-mOtfz5MBlTmYawfmXWBhD43uY
### Find All
GET http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

### Find One
GET http://localhost:3001/api/user/63becc87417557f3ed31bf9c
Content-Type: application/json
Authorization: Bearer {{token}}
