
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2JlY2M4NzQxNzU1N2YzZWQzMWJmOWMiLCJmaXJzdE5hbWUiOiJndXkxMTEiLCJsYXN0TmFtZSI6ImNvaGVuIiwiZW1haWwiOiJndXljb2hlbjg1QGdtYWlsLmNvbSIsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTY3NTY2OTE2OSwiZXhwIjoxNzA3MjI2NzY5fQ.vgRgWMJROtfYHQiqw5d3xMOk4b4nkbB13iCRHEQLS10
### Find All
GET http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

### Find One
GET http://localhost:3001/api/user/63becc87417557f3ed31bf9c
Content-Type: application/json
Authorization: Bearer {{token}}

### Create
POST http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"firstName": "new1",
	"lastName": "user",
	"password": "123123",
	"email": "newuser1@gmail.com"
}

### Update
PUT http://localhost:3001/api/user/63c504a8c580941a6f2ecbd3
Content-Type: application/json
Authorization: Bearer {{token}}

{
	"firstName": "guy11121",
	"lastName": "cohen",
	"roles": ["editor1"]
}

### Delete
DELETE http://localhost:3001/api/user/63c590e8c580941a6f2ecbe4
Content-Type: application/json
Authorization: Bearer {{token}}
