
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzY4ZjQ2MDUzNTkyMzBlMzRiNGE2NyIsImVtYWlsIjoiZ3V5Y29oZW44NUBnbWFpbC5jb20iLCJmaXJzdE5hbWUiOiJndXkiLCJsYXN0TmFtZSI6ImNvaGVuIiwiaWF0IjoxNjY5NjQ0NjM1LCJleHAiOjE2Njk2NTM2MzV9.82aSMVnXiygEhQm0IHC9fz-icMg7qm0Bf35CwOqD7bs

### Find All
GET http://localhost:3001/api/user
Content-Type: application/json
Authorization: Bearer {{token}}

### Find One
GET http://localhost:3001/api/user/63768f4605359230e34b4a671
Content-Type: application/json
Authorization: Bearer {{token}}
